In [ ]:
import torch
from torch import nn

In [ ]:
x=torch.randn(100,3)

layer=nn.Linear(3,5)

print(layer(x).shape)

print(layer.weight)


print(layer.bias)

print(layer.weight.shape)
print(layer.bias.shape)



torch.Size([100, 5])
Parameter containing:
tensor([[-0.3443, -0.3196, -0.5471],
        [ 0.1691,  0.0701,  0.2626],
        [ 0.1779, -0.0408,  0.5330],
        [ 0.0573,  0.2442, -0.2297],
        [-0.3100,  0.5203,  0.1177]], requires_grad=True)
Parameter containing:
tensor([-0.4161, -0.3515,  0.1002, -0.3103, -0.3971], requires_grad=True)
torch.Size([5, 3])
torch.Size([5])


In [ ]:
x=torch.randn(2,5)
print(x)
layer=nn.ReLU()
print(layer(x))

tensor([[ 0.5190, -1.2197, -1.0482, -0.3229,  2.3520],
        [ 0.8691, -0.3860, -0.1348,  2.2520, -1.7673]])
tensor([[0.5190, 0.0000, 0.0000, 0.0000, 2.3520],
        [0.8691, 0.0000, 0.0000, 2.2520, 0.0000]])


In [ ]:
x = torch.randn(3,7)
drop = nn.Dropout(p=0.3) # p는 죽일 확률
print(drop(x))
print(drop(layer(x)))
print(x)

tensor([[-4.7089e-01,  3.8450e+00,  1.5782e+00,  2.3977e+00,  0.0000e+00,
          8.2463e-01, -7.1242e-01],
        [-1.0330e+00, -6.1246e-02, -1.9543e-01, -3.6607e-01,  4.8149e-01,
          0.0000e+00, -4.7378e-02],
        [-0.0000e+00, -8.4545e-01, -1.3773e-03, -0.0000e+00,  0.0000e+00,
         -1.0632e-01,  2.9108e+00]])
tensor([[0.0000, 3.8450, 1.5782, 2.3977, 1.3224, 0.8246, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.4815, 3.8404, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]])
tensor([[-3.2962e-01,  2.6915e+00,  1.1047e+00,  1.6784e+00,  9.2566e-01,
          5.7724e-01, -4.9870e-01],
        [-7.2308e-01, -4.2872e-02, -1.3680e-01, -2.5625e-01,  3.3704e-01,
          2.6883e+00, -3.3164e-02],
        [-1.6471e-01, -5.9181e-01, -9.6414e-04, -5.2173e-01,  6.3789e-01,
         -7.4426e-02,  2.0376e+00]])


In [ ]:
class sample_model(nn.Module):
    def __init__(self):
        super().__init__()
        self.drop_layer=nn.Sequential(nn.Linear(5,7),
                                      nn.Dropout(p=0.3))

    def forward(self, x):
        x = self.drop_layer(x)
        return x


In [ ]:
model=sample_model()
model.train() # train mode로 전환
x=torch.randn(3,5) # 그 담에 x=torch.randn(2,3,5)
print(model(x))

model.eval()
print(model(x)) # test mode

tensor([[ 0.0000, -0.0000, -0.4907,  0.0000, -2.0734,  1.2195,  0.5401],
        [ 0.0000, -0.1516, -0.0000, -0.0000,  0.0746, -0.0000,  1.1787],
        [ 0.0000, -0.1618, -0.5649,  0.0000, -0.7447,  0.3295,  1.3778]],
       grad_fn=<MulBackward0>)
tensor([[ 0.0694, -0.8510, -0.3435,  0.9805, -1.4514,  0.8536,  0.3780],
        [ 2.0053, -0.1061, -0.3000, -0.2749,  0.0522, -0.0114,  0.8251],
        [ 1.2637, -0.1133, -0.3955,  0.3968, -0.5213,  0.2306,  0.9644]],
       grad_fn=<AddmmBackward0>)


In [ ]:
layer = nn.Conv2d(in_channels=1, out_channels=2, kernel_size=3, stride=1, padding=1) # stride=1, padding=0 이 디폴트
layer(torch.randn(32,1,5,5)).shape
# nn.Linear(3,5) # 채채 # 얘는 채 또는 개채를 원함, 개 x 3
# nn.Conv2d(3,5) # 채채 # 얘는 채행열 또는 개채행열을 원함, 개 x 3 x 행 x 열

torch.Size([32, 2, 5, 5])

In [ ]:
layer = nn.Conv2d(3,5,3, stride=2, padding=1)
print(layer(torch.randn(32,3,5,5)).shape)
print(layer.weight.shape)

torch.Size([32, 5, 3, 3])
torch.Size([5, 3, 3, 3])


In [ ]:
conv1 = nn.Conv2d(1,8,6,stride=2)
x=torch.randn(32,1,28,28)
print(conv1(x).shape)

conv2 = nn.Conv2d(8,16,3,padding=1)
print(conv2(conv1(x)).shape)

Maxpool = nn.MaxPool2d(kernel_size=2, stride=(2,2))
print(Maxpool(conv2(conv1(x))).shape)

torch.Size([32, 8, 12, 12])
torch.Size([32, 16, 12, 12])
torch.Size([32, 16, 6, 6])


In [ ]:
maxpool = nn.MaxPool2d(4) # 2 로만 줘도 자동 kernel_size=2, stride=(2,2)
x=torch.randn(1,1,8,8)
print(x)
print(maxpool(x))
print(maxpool(torch.randn(32,3,8,8)).shape)


tensor([[[[ 0.6979, -2.8031,  1.5811,  0.7361,  0.7588,  0.5391, -1.3066,
           -1.2260],
          [ 0.2088, -0.9669, -0.1463,  0.8549,  0.8714, -0.4092,  0.8817,
           -0.1840],
          [-1.7894, -0.9290,  2.1745, -0.0454,  0.4706,  0.5936, -0.0477,
           -0.1046],
          [ 1.1075, -1.9443,  1.0277, -0.3216, -0.7225, -0.0291, -0.2647,
           -1.5959],
          [-1.4454, -1.3951, -1.1690,  0.5841,  0.6364, -0.3690,  2.5397,
           -0.3053],
          [ 0.7959,  0.4568, -0.2122, -0.4690,  0.5163,  0.7784,  0.6434,
            0.1204],
          [ 0.2737,  1.5580,  0.0036, -1.5517, -0.9028, -0.7793, -0.4494,
           -0.8850],
          [-1.6488, -1.3440,  0.4478,  0.8168,  0.8037,  0.6106,  0.9960,
            2.7361]]]])
tensor([[[[2.1745, 0.8817],
          [1.5580, 2.7361]]]])
torch.Size([32, 3, 2, 2])


In [ ]:
avgpool=nn.AvgPool2d(2)
x=torch.randn(1,1,6,6)
print(x)
print(avgpool(x))
print(avgpool(torch.randn(32,3,6,6)).shape)

tensor([[[[-0.3059,  0.5778, -0.0489,  0.4915,  1.0504, -1.9143],
          [ 0.9002, -0.6218, -1.0827,  2.3156, -0.9094, -1.2639],
          [-0.4889, -0.1289,  0.7379, -0.8880, -0.0925,  1.4480],
          [ 0.3860,  0.3648,  1.7569,  0.5379, -0.2475, -1.5379],
          [-0.3513, -1.9646, -0.1031,  0.1279,  1.3176,  0.4675],
          [-1.5648,  0.1580,  0.2415, -1.6949,  0.2113, -0.3966]]]])
tensor([[[[ 0.1376,  0.4189, -0.7593],
          [ 0.0332,  0.5362, -0.1075],
          [-0.9307, -0.3571,  0.4000]]]])
torch.Size([32, 3, 3, 3])


In [ ]:
class CNN(nn.Module):
    def __init__(self):
        super().__init__()

        self.conv1 = nn.Conv2d(1,8,6,stride=2)
        self.conv2 = nn.Conv2d(8,16,3,padding=1)
        self.Maxpool2 = nn.MaxPool2d(2)
        self.fc = nn.Linear(16*6*6,10)

    def forward(self, x):
        x = self.conv1(x)
        x = self.conv2(x)
        x = self.Maxpool2(x)
        # x = torch.flatten(x, start_dim=1)
        # x = self.fc(x)
        return x

x = torch.randn(32,1,28,28)
model = CNN()
print(model(x).shape) # conv 풀링 한 결과  # 16 6 6 576개로 한줄로 연결





torch.Size([32, 16, 6, 6])


## .parameters() vs .modules() vs .children() 그리고 isinstance의 활용

In [ ]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Sequential(nn.Linear(2,3),
                                 nn.ReLU())
        self.fc2 = nn.Sequential(nn.Linear(3,4),
                                 nn.ReLU())
        self.fc_out = nn.Sequential(nn.Linear(4,1),
                                    nn.Sigmoid())
    def forward(self,x):
        x = self.fc1(x)
        x = self.fc2(x)
        x = self.fc_out(x)
        return x

model = MLP()
print(model(torch.randn(2,2)).shape)
print(model)

torch.Size([2, 1])
MLP(
  (fc1): Sequential(
    (0): Linear(in_features=2, out_features=3, bias=True)
    (1): ReLU()
  )
  (fc2): Sequential(
    (0): Linear(in_features=3, out_features=4, bias=True)
    (1): ReLU()
  )
  (fc_out): Sequential(
    (0): Linear(in_features=4, out_features=1, bias=True)
    (1): Sigmoid()
  )
)


In [ ]:
model.parameters()
print(list(model.parameters())[0])

print(list(model.parameters())[1])
# [layer0 weight 값, layer0 bias 값, layer1 weight 값, layer1 bias 값, ...]

Parameter containing:
tensor([[ 0.3237,  0.1387],
        [ 0.0452, -3.0636],
        [ 1.2859,  0.2074]])
Parameter containing:
tensor([ 0.3472,  0.6106, -0.1570])


In [ ]:
# for tranfer learning
model=MLP()
print([p for p in model.parameters() if p.requires_grad])

for p in model.parameters(): # 전체 freeze
    p.requires_grad=False

model.fc_out = nn.Linear(4,10)



params = [p for p in model.parameters() if p.requires_grad]

print(params,'require')

from torch import optim
optimizer = optim.Adam(params, lr=0.1)

[Parameter containing:
tensor([[-0.1788,  0.1292],
        [-0.5436,  0.1273],
        [ 0.5637,  0.5020]], requires_grad=True), Parameter containing:
tensor([ 0.3472,  0.6106, -0.1570], requires_grad=True), Parameter containing:
tensor([[ 0.5179,  0.4328,  0.3044],
        [-0.1159, -0.4901, -0.3969],
        [ 0.0360,  0.1860, -0.3220],
        [ 0.1766, -0.3561,  0.2473]], requires_grad=True), Parameter containing:
tensor([-0.4587, -0.2522,  0.0977, -0.0780], requires_grad=True), Parameter containing:
tensor([[ 0.2240,  0.0542,  0.3395, -0.1105]], requires_grad=True), Parameter containing:
tensor([0.4700], requires_grad=True)]
[Parameter containing:
tensor([[-1.1463e-01,  4.2684e-02, -4.0671e-01, -4.1267e-01],
        [ 1.7450e-01,  2.0466e-01,  3.5381e-04,  4.6763e-01],
        [-1.2868e-01,  5.9359e-02,  3.1228e-01,  3.1341e-01],
        [-3.4640e-01, -2.0882e-01,  1.0743e-01,  1.0936e-01],
        [ 8.5431e-04,  1.4096e-02, -2.6400e-01, -9.0131e-02],
        [-2.4989e-01,  2.5816

In [ ]:
print(list(model.named_parameters())[0])
print(list(model.named_parameters())[1])
list(model.named_parameters())[1]

# [('layer0.weight', weight 값), ('layer0.bias', bias 값), ('layer1.weight', weight 값), ('layer1.bias', bias 값), ...]

('fc1.0.weight', Parameter containing:
tensor([[-0.1788,  0.1292],
        [-0.5436,  0.1273],
        [ 0.5637,  0.5020]]))
('fc1.0.bias', Parameter containing:
tensor([ 0.3472,  0.6106, -0.1570]))


('fc1.0.bias',
 Parameter containing:
 tensor([ 0.3472,  0.6106, -0.1570]))

In [ ]:
for name, p in model.named_parameters():
    print(name)
    print(p)

fc1.0.weight
Parameter containing:
tensor([[-0.1788,  0.1292],
        [-0.5436,  0.1273],
        [ 0.5637,  0.5020]])
fc1.0.bias
Parameter containing:
tensor([ 0.3472,  0.6106, -0.1570])
fc2.0.weight
Parameter containing:
tensor([[ 0.5179,  0.4328,  0.3044],
        [-0.1159, -0.4901, -0.3969],
        [ 0.0360,  0.1860, -0.3220],
        [ 0.1766, -0.3561,  0.2473]])
fc2.0.bias
Parameter containing:
tensor([-0.4587, -0.2522,  0.0977, -0.0780])
fc_out.weight
Parameter containing:
tensor([[-1.1463e-01,  4.2684e-02, -4.0671e-01, -4.1267e-01],
        [ 1.7450e-01,  2.0466e-01,  3.5381e-04,  4.6763e-01],
        [-1.2868e-01,  5.9359e-02,  3.1228e-01,  3.1341e-01],
        [-3.4640e-01, -2.0882e-01,  1.0743e-01,  1.0936e-01],
        [ 8.5431e-04,  1.4096e-02, -2.6400e-01, -9.0131e-02],
        [-2.4989e-01,  2.5816e-01, -4.9882e-01, -1.7129e-01],
        [-4.6960e-02, -3.9193e-01, -1.3771e-01, -3.3582e-01],
        [ 3.3708e-01, -2.6636e-01,  2.9797e-01, -3.6517e-01],
        [-4.2719e

In [ ]:
model.modules()
list(model.modules())

[MLP(
   (fc1): Sequential(
     (0): Linear(in_features=2, out_features=3, bias=True)
     (1): ReLU()
   )
   (fc2): Sequential(
     (0): Linear(in_features=3, out_features=4, bias=True)
     (1): ReLU()
   )
   (fc_out): Linear(in_features=4, out_features=10, bias=True)
 ),
 Sequential(
   (0): Linear(in_features=2, out_features=3, bias=True)
   (1): ReLU()
 ),
 Linear(in_features=2, out_features=3, bias=True),
 ReLU(),
 Sequential(
   (0): Linear(in_features=3, out_features=4, bias=True)
   (1): ReLU()
 ),
 Linear(in_features=3, out_features=4, bias=True),
 ReLU(),
 Linear(in_features=4, out_features=10, bias=True)]

In [ ]:
print([m for m in model.modules() if isinstance(m,nn.Linear)])
print([m.weight for m in model.modules() if isinstance(m,nn.Linear)])
print([m.weight.grad for m in model.modules() if isinstance(m,nn.Linear)])

[Linear(in_features=2, out_features=3, bias=True), Linear(in_features=3, out_features=4, bias=True), Linear(in_features=4, out_features=10, bias=True)]
[Parameter containing:
tensor([[-0.1788,  0.1292],
        [-0.5436,  0.1273],
        [ 0.5637,  0.5020]]), Parameter containing:
tensor([[ 0.5179,  0.4328,  0.3044],
        [-0.1159, -0.4901, -0.3969],
        [ 0.0360,  0.1860, -0.3220],
        [ 0.1766, -0.3561,  0.2473]]), Parameter containing:
tensor([[-1.1463e-01,  4.2684e-02, -4.0671e-01, -4.1267e-01],
        [ 1.7450e-01,  2.0466e-01,  3.5381e-04,  4.6763e-01],
        [-1.2868e-01,  5.9359e-02,  3.1228e-01,  3.1341e-01],
        [-3.4640e-01, -2.0882e-01,  1.0743e-01,  1.0936e-01],
        [ 8.5431e-04,  1.4096e-02, -2.6400e-01, -9.0131e-02],
        [-2.4989e-01,  2.5816e-01, -4.9882e-01, -1.7129e-01],
        [-4.6960e-02, -3.9193e-01, -1.3771e-01, -3.3582e-01],
        [ 3.3708e-01, -2.6636e-01,  2.9797e-01, -3.6517e-01],
        [-4.2719e-01,  2.6969e-01, -3.9163e-01,  

In [ ]:
# weight initialization에 활용
for m in model.modules():
    if isinstance(m, nn.Linear):
        nn.init.kaiming_normal_(m.weight)

        # nn.init.constant_(m.weight, 1)

print([m.weight for m in model.modules() if isinstance(m, nn.Linear)])




[Parameter containing:
tensor([[ 0.3237,  0.1387],
        [ 0.0452, -3.0636],
        [ 1.2859,  0.2074]]), Parameter containing:
tensor([[-1.1097,  0.3776, -0.8122],
        [-0.6587, -1.3300, -2.1618],
        [ 0.0735,  0.5016,  0.4132],
        [-1.1519,  0.4531, -0.5332]]), Parameter containing:
tensor([[ 0.9027,  0.2210, -0.0667,  0.1051],
        [ 0.6767,  0.8527, -1.1430, -0.0521],
        [ 0.1274,  0.3082, -0.8691,  0.4342],
        [ 0.5686,  0.6143, -0.5782, -0.5028],
        [ 0.4461,  0.1708, -0.1354,  0.5796],
        [ 1.5199,  0.4332, -0.1716,  1.2500],
        [ 0.7515, -0.1549,  0.3757, -0.5571],
        [ 0.8202,  0.7561,  0.3484, -0.0305],
        [-0.1452,  0.0118, -0.2169,  0.3432],
        [-0.2231, -0.3241,  0.5050,  0.4680]], requires_grad=True)]


In [61]:
#@title MODEL CHILDREN
model.children()
list(model.children())

[Sequential(
   (0): Linear(in_features=2, out_features=3, bias=True)
   (1): ReLU()
 ),
 Sequential(
   (0): Linear(in_features=3, out_features=4, bias=True)
   (1): ReLU()
 ),
 Linear(in_features=4, out_features=10, bias=True)]

In [62]:
x = torch.randn(2,2)
list(model.children())[0](x)

tensor([[0.6355, 0.0000, 0.7692],
        [0.4486, 0.0000, 0.0000]])

In [63]:
print(*list(model.children())[:2])
sub_network = nn.Sequential(*list(model.children())[:2])
print(sub_network)
print(sub_network(x))

Sequential(
  (0): Linear(in_features=2, out_features=3, bias=True)
  (1): ReLU()
) Sequential(
  (0): Linear(in_features=3, out_features=4, bias=True)
  (1): ReLU()
)
Sequential(
  (0): Sequential(
    (0): Linear(in_features=2, out_features=3, bias=True)
    (1): ReLU()
  )
  (1): Sequential(
    (0): Linear(in_features=3, out_features=4, bias=True)
    (1): ReLU()
  )
)
tensor([[0.0000, 0.0000, 0.4623, 0.0000],
        [0.0000, 0.0000, 0.1307, 0.0000]])


## ModuleList vs Sequential


In [64]:
fc=nn.Linear(3,3)
layer_list = [fc for _ in range(5)]
layers1 = nn.Sequential(*layer_list)



layers2 = nn.ModuleList(layer_list)
print(layers1)
print(layers2)

x=torch.randn(1,3)
print(layers1(x))

# print(layers2(x)) # error!   forward 가 정의 안됨
for layer in layers2:
    x = layer(x)
print(x)

Sequential(
  (0): Linear(in_features=3, out_features=3, bias=True)
  (1): Linear(in_features=3, out_features=3, bias=True)
  (2): Linear(in_features=3, out_features=3, bias=True)
  (3): Linear(in_features=3, out_features=3, bias=True)
  (4): Linear(in_features=3, out_features=3, bias=True)
)
ModuleList(
  (0-4): 5 x Linear(in_features=3, out_features=3, bias=True)
)
tensor([[-0.0386,  1.0841, -0.3481]], grad_fn=<AddmmBackward0>)
tensor([[-0.0386,  1.0841, -0.3481]], grad_fn=<AddmmBackward0>)


In [65]:
# 걍 리스트 쓰지 왜 nn.ModuleList 를 쓸까?
class testNet(nn.Module):
    def __init__(self):
        super().__init__()

        # self.Module_List = [nn.Linear(3,3), nn.Linear(3,3)]
        self.Module_List = nn.ModuleList([nn.Linear(3,3), nn.Linear(3,3)])

    def forward(self,x):
        for layer in self.Module_List:
            x = layer(x)
        return x

model=testNet()
print(model(torch.randn(1,3)))

print(model) # 그냥 리스트로 하면 등록이 안돼있다!

optimizer = optim.Adam(model.parameters(), lr = 0.1) # 등록이 안돼있으면 parameter를 못 찾는다!

tensor([[ 0.0486, -0.5218, -0.8401]], grad_fn=<AddmmBackward0>)
testNet(
  (Module_List): ModuleList(
    (0-1): 2 x Linear(in_features=3, out_features=3, bias=True)
  )
)


In [ ]:
# 그럼 nn.Sequential 쓰고 말지 왜 굳이 nn.ModuleList?
class small_block(nn.Module):
    def __init__(self):
        super().__init__()
        self.block_x = nn.Linear(1,1)
        self.block_y = nn.Linear(1,1)

    def forward(self, x, y):
        x = self.block_x(x)
        y = self.block_y(y)
        return x, y

block = small_block()
print(block)
model = nn.Sequential(block, block)
print(model)
# model(torch.randn(1), torch.randn(1)) # error!
# nn.Sequential 이 가지고 있는 forward 함수를 call 하기 때문에 입력을 두 개 넣으면 안된다!!

model = nn.ModuleList([block,block])
x = torch.randn(1)
y = torch.randn(1)
for block in model:
    x, y = block(x,y)
print(x, y)